image: docker:latest
services:
  - docker:dind

include:
  # tests
  - local: .gitlab-ci/tests/api-tests.yaml
  - local: .gitlab-ci/tests/e2e-tests.yaml

  # deploy
  - local: .gitlab-ci/deploy/deploy-test-installation.yaml
  - local: .gitlab-ci/deploy/publish-images.yaml

variables:
  DEPLOY_TEST_INSTALLATION:
    value: "false"
    description: "Build test installation"
    options:
      - "true"
      - "false"
  RUN_E2E_TESTS:
    value: "false"
    description: "Run E2E tests"
    options:
      - "true"
      - "false"
  RUN_API_TESTS:
    value: "false"
    description: "Run API tests"
    options:
      - "true"
      - "false"

  # Nazwa projektu w GCR
  GCP_PROJECT_ID: "mythic-fire-446020-d5"
  GCR_REGISTRY: "gcr.io"
  IMAGE_TAG: "latest"
  API_IMAGE_NAME: "api"
  APP_IMAGE_NAME: "app"

stages:
  - build
  - tests
