image: docker:latest
services:
  - docker:dind

include:
  - local: .gitlab-ci/tests/api-tests.yaml
  - local: .gitlab-ci/tests/e2e-tests.yaml

  - local: .gitlab-ci/deploy/deploy-test-installation.yaml
  - local: .gitlab-ci/deploy/publish-images.yaml

variables:
  DEPLOY_TEST_INSTALLATION:
    value: "false"
    description: "Build test installation"
    options:
      - "true"
      - "false"
  RUN_E2E_TESTS:
    value: "false"
    description: "Run E2E tests"
    options:
      - "true"
      - "false"
  RUN_API_TESTS:
    value: "false"
    description: "Run API tests"
    options:
      - "true"
      - "false"

  GCP_PROJECT_ID: "mythic-fire-446020-d5"
  GCP_REGION: "europe-west1"
  GCP_CLUSTER_NAME: 'app-testing'

stages:
  - build
  - tests
