apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80          # Port, na którym użytkownicy łączą się z aplikacją
      targetPort: 80  # Port aplikacji w kontenerze
