deploy-test-installation:
  image: google/cloud-sdk:alpine
  stage: build
  before_script:
    - source .gitlab-ci/deploy/google-cloud-setup.sh
  script:
    - gcloud container clusters get-credentials ${GCP_CLUSTER_NAME} --region ${GCP_REGION} --project $GCP_PROJECT_ID
    - kubectl config use-context gke_${GCP_PROJECT_ID}_${GCP_REGION}_${GCP_CLUSTER_NAME}
    - kubectl delete namespace test-installation --ignore-not-found=true
    - kubectl create namespace test-installation
    - kubectl apply -f deployment/api/deployment.yaml -n test-installation
    - kubectl apply -f deployment/api/service.yaml -n test-installation
    - kubectl apply -f deployment/gui/deployment.yaml -n test-installation
    - kubectl apply -f deployment/gui/service.yaml -n test-installation
  rules:
    - if: $DEPLOY_TEST_INSTALLATION == "true"
  needs:
    - job: publish-images
