publish-images:
  stage: build
  script:
    - source .gitlab-ci/deploy/google-cloud-setup.sh
    - docker build -t gcr.io/${GCP_PROJECT_ID}/api:latest -f app/api/Dockerfile app/api
    - docker push gcr.io/${GCP_PROJECT_ID}/api:latest
    - docker build -t gcr.io/${GCP_PROJECT_ID}/gui:latest -f app/gui/Dockerfile app/gui
    - docker push gcr.io/${GCP_PROJECT_ID}/gui:latest
  rules:
    - if: >-
        $DEPLOY_TEST_INSTALLATION == "true"
