publish-images:
  stage: build
  script:
    - source .gitlab-ci/deploy/google-cloud-setup.sh
    - docker build -t gcr.io/mythic-fire-446020-d5/api:$IMAGE_TAG -f app/api/Dockerfile app/api
    - docker push gcr.io/mythic-fire-446020-d5/api:$IMAGE_TAG
    - docker build -t gcr.io/mythic-fire-446020-d5/gui:$IMAGE_TAG -f app/gui/Dockerfile app/gui
    - docker push gcr.io/mythic-fire-446020-d5/gui:$IMAGE_TAG
  rules:
    - if: >-
        $DEPLOY_TEST_INSTALLATION == "true"
